# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 436e29c21653bafb9905f08c11f110e3ca1160d6f072061bfd932f1d13c8c9c62c4e767545d3d322354bb39b5da49006ee38651f6a86c455cb5e66304e73d3f0

test:
  secret_key_base: 02615129dd913a78d0870942bbe6053f1bad725703ec9bac676f304cb8ccf1f01547b1bdcdb70efbb6a5a77ad8984eea3b3af3c9501168ab64396d487de892ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
